package university.enums;

public enum Department {
    SCHOOL_OF_ENERGY_AND_PETROLEUM,
    SCHOOL_OF_GEOLOGY,
    SCHOOL_OF_INFORMATION_TECHNOLOGY_AND_ENGINEERING,
    BUSINESS_SCHOOL,
    SCHOOL_OF_INTERNATIONAL_ECONOMICS,
    KAZAKHSTAN_MARITIME_ACADEMY,
    SCHOOL_OF_APPLIED_MATHEMATICS,
    SCHOOL_OF_CHEMICAL_ENGINEERING,
    SCHOOL_OF_SOCIAL_SCIENCES,
    SCHOOL_OF_MATERIAL_SCIENCE_AND_GREEN_TECHNOLOGIES
}
